:memo: README.md
Dedetat/powerpuff-yourself pull request #27
Opened 2017-10-12 15:39 UTC by fabienjuif

2017-10-12 15:40 UTC, fabienjuif commented
Hmm, styles are not all there :(

2017-10-12 15:41 UTC, fabienjuif commented
What I wanted is 
![image](https://user-images.githubusercontent.com/17828231/31505167-911c705c-af74-11e7-80bf-a7de117d65bf.png)

2017-10-16 12:00 UTC, delphinemillet requested changes
revision

2017-10-16 12:00 UTC, delphinemillet commented on README.md
> + - Source code of our livecoding are described here too ! 📖
Source code of our livecoding `is`

2017-10-16 12:00 UTC, delphinemillet commented on README.md
> + 2. `types` is used to ... types fields 👌, we can already use it to describe models ! And  `types.model` is the way to go !
to ... `type` fields

2017-10-16 12:00 UTC, delphinemillet commented on README.md
> + 7. Let's instanciate our powerpuff, it will be... hm... `Rebelle` (this is Blossum in french, sorry)
Blossom

2017-10-16 12:00 UTC, delphinemillet commented on README.md
> + 9. it works :tada:
majuscule

2017-10-16 12:00 UTC, delphinemillet commented on README.md
> + 6. 🤔 oups, it doesn't work at all ! This is because, by default, a type is required.
a `field` is required

2017-10-16 12:10 UTC, delphinemillet commented
it seems that Github sanitize markdown before convert it to Markdown so style attributes are ignored

2017-10-16 14:13 UTC, fabienjuif commented
I can remove our avatar then. 
What do you think ?

2017-10-16 14:19 UTC, delphinemillet commented
it's ok to me 👍

2017-10-16 14:42 UTC, delphinemillet commented on README.md
> +> Write our first model about a **Powerpuff**, we can call it `Powerpuff` (damn, clever)
model `of` Powerpuff

2017-10-16 15:11 UTC, delphinemillet approved these changes

2017-10-16 15:12 UTC, merged